import { Device } from './types';

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev_001',
    name: 'Industrial Diesel Generator',
    type: 'Generator',
    description: 'Main backup power unit for Sector 7.',
    status: 'stopped',
    currentScenario: 'Normal Operation',
    scenarios: ['Normal Operation', 'High Load', 'Fuel Line Blockage', 'Coolant Leak'],
    metrics: [
      { id: 'rpm', name: 'RPM', unit: 'rpm', min: 0, max: 3000 },
      { id: 'temp', name: 'Temperature', unit: '°C', min: 20, max: 120 },
      { id: 'voltage', name: 'Output Voltage', unit: 'V', min: 0, max: 480 },
      { id: 'vibration', name: 'Vibration', unit: 'mm/s', min: 0, max: 10 },
    ],
  },
  {
    id: 'dev_002',
    name: 'Plasma Cutter Arm',
    type: 'Cutter',
    description: 'Precision CNC plasma cutter.',
    status: 'stopped',
    currentScenario: 'Precision Cutting',
    scenarios: ['Precision Cutting', 'Rapid Traverse', 'Nozzle Clog', 'Arc Stability Loss'],
    metrics: [
      { id: 'current', name: 'Arc Current', unit: 'A', min: 0, max: 100 },
      { id: 'gasPressure', name: 'Gas Pressure', unit: 'psi', min: 0, max: 120 },
      { id: 'x_pos', name: 'X Position', unit: 'mm', min: 0, max: 1000 },
      { id: 'head_temp', name: 'Head Temp', unit: '°C', min: 20, max: 200 },
    ],
  },
];

export const DICTIONARY = {
  en: {
    title: 'DeviceSimulator',
    devices: 'Devices',
    addDevice: 'Add Device',
    running: 'Running',
    stopped: 'Stopped',
    simulationMode: 'Simulation Mode',
    modeAI: 'AI (Gemini)',
    modeLocal: 'Local (Physics)',
    scenario: 'Scenario',
    logs: 'System Logs',
    telemetry: 'Real-time Telemetry',
    start: 'Start',
    stop: 'Stop',
    create: 'Create',
    cancel: 'Cancel',
    name: 'Name',
    type: 'Type',
    scenarios: 'Scenarios (comma separated)',
    metrics: 'Metrics',
    dashboard: 'Dashboard',
    digitalTwin: '3D Digital Twin',
    systemSettingsGroup: 'System Settings',
    basicSettingsGroup: 'Basic Settings',
    connectSettings: 'Connect Settings',
    deviceConfig: 'Device Config',
    parameterSettings: 'Parameter Settings',
    llmSettings: 'LLM Settings',
    resetDefaults: 'Reset to Defaults',
    globalConfigTitle: 'Global System Configuration',
    globalConfigDesc: 'These settings affect the global behavior of the simulation engine and data storage.',
    generalSettings: 'General Settings',
    defaultSamplingRate: 'Default Sampling Rate (ms)',
    samplingRateDesc: 'Base frequency for data generation',
    maxBatchSize: 'Max Batch Size',
    batchSizeDesc: 'Maximum records per write operation',
    maxConcurrentDevices: 'Max Concurrent Devices',
    logLevel: 'Log Level',
    advancedFeatures: 'Advanced Features',
    enablePhysics: 'Enable Physics Engine',
    physicsDesc: 'Use local physics calculation for simulation',
    enableAI: 'Enable AI Generation',
    aiDesc: 'Allow Gemini AI to generate simulation data',
    dataRetention: 'Data Retention Policy (Days)',
    day: 'Day',
    days: 'Days',
    llmConfig: 'LLM Configuration',
    apiKey: 'API Key',
    provider: 'Provider',
    currentActive: 'Current Active Provider',
    baseUrl: 'Base URL',
    modelName: 'Model Name',
    aiAutoFill: 'AI Auto-Fill Schema',
    categoryConfig: 'Category Config',
    modelConfig: 'Model Config',
    visualModelConfig: 'Visual Model Config',
    visualModelDesc: 'Manage 3D models and simulation templates.',
    dashboardTitle: 'System Dashboard',
    aiReport: 'AI Diagnosis',
    statusDistribution: 'Status Distribution',
    categoryDistribution: 'Category Distribution',
    topComplexDevices: 'Top Devices by Complexity',
    totalDevices: 'Total Devices',
    activeDevices: 'Active Devices',
    uptime: 'Uptime',
    dataThroughput: 'Data Throughput',
    avgMetrics: 'Avg. Metrics',
    ptsPerSec: 'pts/s',
    metricsCount: 'Metrics Count',
    allDevices: 'All Devices',
    clearFilters: 'Clear Filters',
    all: 'All',
    noDevicesFound: 'No devices found matching current filters.',
    noDescription: 'No description available.',
    realTimeMetrics: 'Real-time Metrics',
    switchGrid: 'Switch to Grid View',
    switchList: 'Switch to List View',
    waitingData: 'Waiting for data...',
    
    // Device Manager
    deviceManagement: 'Device Management',
    refresh: 'Refresh',
    newDevice: 'New Device',
    deleteDeviceConfirm: 'Are you sure you want to delete this device?',
    deleteFailed: 'Failed to delete device',
    saveFailed: 'Failed to save device',
    editDevice: 'Edit Device',
    createDevice: 'Create Device',
    basicInfo: 'Basic Info',
    parameters: 'Parameters',
    deviceName: 'Device Name',
    samplingRate: 'Sampling Rate (ms)',
    description: 'Description',
    defineMetrics: 'Define the metrics this device generates.',
    addParameter: 'Add Parameter',
    paramName: 'Name',
    paramType: 'Type',
    paramUnit: 'Unit',
    paramMin: 'Min',
    paramMax: 'Max',
    paramGenMode: 'Gen Mode',
    paramIsTag: 'Is Tag',
    tagColumn: 'Column',
    tagTag: 'Tag',
    tagHint: 'Tags are metadata for grouping, Columns store time-series data',
    defaultValue: 'Default Value',
    tagDefaultHint: 'Tag value for subtable',
    save: 'Save',
    loadParamsConfirm: 'Load parameters from this category template? This will replace current parameters.',
    noParams: 'No parameters defined. Add one to start generating data.',
    saveDevice: 'Save Device',
    searchDevice: 'Search devices...',
    allCategories: 'All Categories',
    subTableName: 'TDengine Subtable Name',
    importDevices: 'Batch Import',
    invalidImportFormat: 'Invalid format: Expected a JSON array of devices',
    importCompleted: 'Import completed',
    importError: 'Error importing file',
    exportDevices: 'Batch Export',
    noDevicesToExport: 'No devices to export matching current filters',
    success: 'success',
    subTableHint: 'This is the actual table name in TDengine used for data storage.',
    autoGenerated: 'Auto-generated',
    batchDelete: 'Batch Delete',
    confirmBatchDelete: 'Are you sure you want to delete {count} selected devices?',
    selectMode: 'Select Mode',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    deleteSelected: 'Delete Selected',
    cleanData: 'Clean Data',
    cleanDataTitle: 'Clean Device Data',
    cleanAll: 'Clean All History',
    cleanRange: 'Clean Time Range',
    startTime: 'Start Time',
    endTime: 'End Time',
    cleaning: 'Cleaning...',
    dataCleaned: 'Data cleaned successfully',
    cleanFailed: 'Failed to clean data',
    generateData: 'Generate Data',
    generateDataTitle: 'Generate Historical Data',
    intervalMs: 'Interval (ms)',
    generating: 'Generating...',
    dataGenerated: 'Data generated successfully',
    generateFailed: 'Failed to generate data',
    playback: 'Playback',
    playbackTitle: 'Historical Playback',
    simulationTitle: 'Simulation',
    monitorTitle: 'Real-time Monitor',
    preview: 'Preview',
    
    // Category Manager
    categoryManagement: 'Category Management',
    scenarioConfig: 'Scenario Config',
    syncSchema: 'Sync Schema',
    newCategory: 'New Category',
    syncConfirm: 'This will create Super Tables in TDengine for all categories. Continue?',
    deleteCategoryConfirm: 'Are you sure you want to delete this category? This may affect associated devices.',
    editCategory: 'Edit Category',
    createCategory: 'Create Category',
    categoryName: 'Category Name',
    categoryCode: 'Category Code (Unique)',
    paramJsonDef: 'Parameters (JSON Definition)',
    paramJsonHint: 'Define parameters as a JSON array. These will be used to create the TDengine Super Table schema.',
    synced: 'Synced',
    failed: 'Failed',
    checkConsole: 'Check console for details',
    invalidJson: 'Invalid JSON',
    saveCategory: 'Save Category',
    deviceCount: 'Device Count',

    // System Manager
    systemMonitor: 'System Monitor',
    systemLogs: 'System Logs',
    tdengineView: 'TDengine View',
    systemStatusTitle: 'System Status & Configuration',
    dataGenService: 'Data Generation Service',
    dataGenDesc: 'Controls the global data generation engine. When running, all active devices will generate data according to their configuration.',
    startAllData: 'Start All Data Generation',
    stopAllData: 'Stop All Data Generation',
    tdengineIntegration: 'TDengine Integration',
    connected: 'Connected',
    disconnected: 'Disconnected',
    host: 'Host',
    port: 'Port',
    enableTdengine: 'Enable TDengine Storage',
    username: 'Username',
    password: 'Password',
    databaseName: 'Database Name',
    saveConfig: 'Save Configuration',
    testConnection: 'Test Connection',
    configSaved: 'Configuration saved successfully',
    connectionTestFailed: 'Connection test failed',
    subtableSettings: 'Subtable Settings',
    subtableNameTemplate: 'Subtable Name Template',
    subtableNameHint: 'Use placeholders: {device_id}, {category_code}, {timestamp}',
    subtableNameExample: 'Example: d_{device_id} → d_dev001',
    
    // Simulation Model Manager
    modelManagement: 'Simulation Model Management',
    newModel: 'New Model',
    deleteModelConfirm: 'Are you sure you want to delete this simulation model?',
    editModel: 'Edit Simulation Model',
    createModel: 'Create Simulation Model',
    modelName: 'Model Name',
    configJson: 'Configuration (JSON)',
    saveModel: 'Save Model',

    // Log Viewer
    noLogs: 'No logs generated yet.',
    aiAnalysis: 'AI Analysis',
    analyzing: 'Analyzing...',
    analysisResult: 'Analysis Result',
    close: 'Close',

    // Add Device Modal
    addMetric: 'Add Metric',
    generic: 'Generic',
    generator: 'Generator',
    cutter: 'Cutter',
    customDeviceDesc: 'Custom user defined device',
    metricIdPlaceholder: 'ID (e.g. rpm)',
    metricNamePlaceholder: 'Name',
    metricUnitPlaceholder: 'Unit',
    twinSuffix: 'TWIN',
    syncPrefix: 'SYNC',
    
    // AI Batch Modal
    aiBatchGeneration: 'AI Batch Generation',
    aiBatchDesc: 'Describe the devices you want to generate. Be specific about quantity, type, and naming.',
    aiBatchPlaceholder: 'e.g., Create 10 Temperature Sensors for Warehouse A, numbered sequentially.',
    aiBatchPoweredBy: 'Powered by active LLM provider (Gemini/DeepSeek)',
    aiBatchButton: 'AI Batch',



    // New Features
    advancedAndErrors: 'Advanced & Errors',
    globalPhysicsConfig: 'Global Physics Configuration',
    massKg: 'Mass (kg)',
    maxVelocity: 'Max Velocity (m/s)',
    paramErrorInjection: 'Parameter Error Injection',
    driftRate: 'Drift Rate (/sec)',
    anomalyProb: 'Anomaly Prob. (0-1)',
    dropProb: 'Drop Prob. (MCAR)',
    noNumericParams: 'No numeric parameters available for error injection.',
    
    general: 'General',
    mqtt: 'MQTT',
    modbus: 'Modbus',
    
    mqttConfig: 'MQTT Configuration',
    brokerHost: 'Broker Host',
    brokerPort: 'Broker Port',
    enableMqttPush: 'Enable MQTT Push',
    topicTemplate: 'Topic Template',
    saveMqttSettings: 'Save MQTT Settings',
    
    modbusTcpServer: 'Modbus TCP Server',
    tcpPort: 'TCP Port',
    enableModbusServer: 'Enable Modbus Server',
    mappingInfo: 'Mapping Info',
    saveModbusSettings: 'Save Modbus Settings',
    
    exportCsv: 'Export CSV',
    
    logicRules: 'Logic Rules',
    addRule: 'Add Rule',
    condition: 'Condition',
    action: 'Action',
    ruleHint: 'e.g. temp > 80',
    actionHint: 'e.g. status = "alarm"',
    createScenario: 'Create AI Scenario',
    scenarioCreated: 'Scenario Created Successfully',
    scenarioPrompt: "Describe the simulation scenario (e.g., 'Coolant leak causing temp spike after 10s'). AI will generate the configuration.",
    scenarioPlaceholder: 'Enter description...',
    generate: 'Generate',
    aiPromptPlaceholder: "Describe scenario (e.g. 'Overheating due to fan failure')...",
    aiSuccess: "AI Scenario Generated Successfully",
    aiFailed: "AI Generation Failed",
  },
  zh: {
    title: 'DeviceSimulator',
    devices: '设备列表',
    addDevice: '添加设备',
    running: '运行中',
    stopped: '已停止',
    simulationMode: '仿真模式',
    modeAI: 'AI 生成 (Gemini)',
    modeLocal: '本地引擎 (物理)',
    scenario: '运行场景',
    logs: '系统日志',
    telemetry: '实时遥测',
    start: '启动',
    stop: '停止',
    create: '创建',
    cancel: '取消',
    name: '设备名称',
    type: '类型',
    scenarios: '场景 (逗号分隔)',
    metrics: '指标',
    dashboard: '仪表盘',
    digitalTwin: '3D 数字孪生',
    systemSettingsGroup: '系统设置',
    basicSettingsGroup: '基础设置',
    connectSettings: '连接设置',
    deviceConfig: '设备配置',
    parameterSettings: '参数设置',
    llmSettings: 'LLM 设置',
    resetDefaults: '重置为默认',
    globalConfigTitle: '全局系统配置',
    globalConfigDesc: '这些设置会影响仿真引擎和数据存储的全局行为。',
    generalSettings: '通用设置',
    defaultSamplingRate: '默认采样率 (ms)',
    samplingRateDesc: '数据生成的基础频率',
    maxBatchSize: '最大批处理大小',
    batchSizeDesc: '每次写入操作的最大记录数',
    maxConcurrentDevices: '最大并发设备数',
    logLevel: '日志级别',
    advancedFeatures: '高级功能',
    enablePhysics: '启用物理引擎',
    physicsDesc: '使用本地物理计算进行仿真',
    enableAI: '启用 AI 生成',
    aiDesc: '允许 Gemini AI 生成仿真数据',
    dataRetention: '数据保留策略 (天)',
    day: '天',
    days: '天',
    llmConfig: 'LLM 配置',
    apiKey: 'API 密钥',
    provider: '提供商',
    currentActive: '当前活动提供商',
    baseUrl: '基础 URL',
    modelName: '模型名称',
    aiAutoFill: 'AI 自动生成架构',
    categoryConfig: '分类配置',
    modelConfig: '模型配置',
    visualModelConfig: '可视化模型配置',
    visualModelDesc: '管理 3D 模型和仿真模板。',
    dashboardTitle: '系统仪表盘',
    aiReport: 'AI 智能诊断',
    statusDistribution: '设备状态分布',
    categoryDistribution: '设备分类统计',
    topComplexDevices: '设备复杂度排行',
    totalDevices: '设备总数',
    activeDevices: '活跃设备',
    uptime: '运行时间',
    dataThroughput: '数据吞吐量',
    avgMetrics: '平均指标数',
    ptsPerSec: '点/秒',
    metricsCount: '指标数量',
    allDevices: '所有设备',
    clearFilters: '清除筛选',
    all: '全部',
    noDevicesFound: '未找到符合当前筛选条件的设备。',
    noDescription: '暂无描述',
    realTimeMetrics: '实时指标',
    switchGrid: '切换至网格视图',
    switchList: '切换至列表视图',
    waitingData: '等待数据...',

    // Device Manager
    deviceManagement: '设备管理',
    refresh: '刷新',
    newDevice: '新建设备',
    deleteDeviceConfirm: '确定要删除此设备吗？',
    deleteFailed: '删除设备失败',
    saveFailed: '保存设备失败',
    editDevice: '编辑设备',
    createDevice: '创建设备',
    basicInfo: '基本信息',
    parameters: '参数',
    deviceName: '设备名称',
    samplingRate: '采样率 (ms)',
    description: '描述',
    defineMetrics: '定义该设备生成的指标。',
    addParameter: '添加参数',
    paramName: '名称',
    paramType: '类型',
    paramUnit: '单位',
    paramMin: '最小值',
    paramMax: '最大值',
    paramGenMode: '生成模式',
    paramIsTag: '字段类型',
    tagColumn: '列',
    tagTag: '标签',
    tagHint: '标签用于分组元数据，列存储时序数据',
    defaultValue: '默认值',
    tagDefaultHint: '子表的标签值',
    save: '保存',
    loadParamsConfirm: '从该分类模板加载参数？这将替换当前参数。',
    noParams: '未定义参数。添加一个以开始生成数据。',
    saveDevice: '保存设备',
    searchDevice: '搜索设备...',
    allCategories: '所有分类',
    subTableName: 'TDengine 子表名称',
    importDevices: '批量导入',
    invalidImportFormat: '格式无效：需要设备 JSON 数组',
    importCompleted: '导入完成',
    importError: '导入文件出错',
    exportDevices: '批量导出',
    noDevicesToExport: '没有匹配当前筛选条件的设备可导出',
    success: '成功',
    subTableHint: '这是 TDengine 中用于存储数据的实际表名。',
    cleanData: '清除数据',
    cleanDataTitle: '清除设备数据',
    cleanAll: '清除所有历史数据',
    cleanRange: '清除指定时间段',
    playbackTitle: '历史回放',
    simulationTitle: '模拟仿真',
    monitorTitle: '实时监测',
    preview: '预览',
    startTime: '开始时间',
    endTime: '结束时间',
    cleaning: '正在清除...',
    dataCleaned: '数据清除成功',
    cleanFailed: '数据清除失败',
    autoGenerated: '自动生成',
    batchDelete: '批量删除',
    confirmBatchDelete: '确定要删除选中的 {count} 个设备吗？',
    selectMode: '选择模式',
    selectAll: '全选',
    deselectAll: '取消全选',
    deleteSelected: '删除选中项',
    
    // Category Manager
    categoryManagement: '分类管理',
    scenarioConfig: '场景配置',
    syncSchema: '同步架构',
    newCategory: '新建分类',
    syncConfirm: '这将为所有分类在 TDengine 中创建超级表。继续？',
    deleteCategoryConfirm: '确定要删除此分类吗？这可能会影响关联设备。',
    editCategory: '编辑分类',
    createCategory: '创建分类',
    categoryName: '分类名称',
    categoryCode: '分类代码 (唯一)',
    paramJsonDef: '参数 (JSON 定义)',
    paramJsonHint: '将参数定义为 JSON 数组。这些将用于创建 TDengine 超级表架构。',
    synced: '已同步',
    failed: '失败',
    checkConsole: '查看控制台了解详情',
    saveCategory: '保存分类',
    deviceCount: '设备数量',

    // System Manager
    systemMonitor: '系统监控',
    systemLogs: '系统日志',
    tdengineView: 'TDengine 视图',
    systemStatusTitle: '系统状态与配置',
    dataGenService: '数据生成服务',
    dataGenDesc: '控制全局数据生成引擎。运行时，所有活动设备将根据其配置生成数据。',
    startAllData: '启动所有数据生成',
    stopAllData: '停止所有数据生成',
    tdengineIntegration: 'TDengine 集成',
    connected: '已连接',
    disconnected: '未连接',
    host: '主机',
    port: '端口',
    enableTdengine: '启用 TDengine 存储',
    username: '用户名',
    password: '密码',
    databaseName: '数据库名称',
    saveConfig: '保存配置',
    testConnection: '测试连接',
    configSaved: '配置保存成功',
    connectionTestFailed: '连接测试失败',
    subtableSettings: '子表设置',
    subtableNameTemplate: '子表名称模板',
    subtableNameHint: '可用占位符: {device_id}, {category_code}, {timestamp}',
    subtableNameExample: '示例: d_{device_id} → d_dev001',
    
    // Simulation Model Manager
    modelManagement: '仿真模型管理',
    newModel: '新建模型',
    deleteModelConfirm: '确定要删除此仿真模型吗？',
    editModel: '编辑仿真模型',
    createModel: '创建仿真模型',
    configJson: '配置 (JSON)',
    saveModel: '保存模型',

    // Log Viewer
    noLogs: '暂无日志。',
    aiAnalysis: 'AI 智能分析',
    analyzing: '正在分析...',
    analysisResult: '分析结果',
    close: '关闭',

    // Add Device Modal
    addMetric: '添加指标',
    generic: '通用',
    generator: '发电机',
    cutter: '切割机',
    customDeviceDesc: '自定义设备',
    metricIdPlaceholder: 'ID (如 rpm)',
    metricNamePlaceholder: '名称',
    metricUnitPlaceholder: '单位',
    twinSuffix: '孪生',
    syncPrefix: '同步',
    
    // New Features
    advancedAndErrors: '高级与故障注入',
    globalPhysicsConfig: '全局物理配置',
    massKg: '质量 (kg)',
    maxVelocity: '最大速度 (m/s)',
    paramErrorInjection: '参数故障注入',
    driftRate: '漂移率 (/秒)',
    anomalyProb: '异常概率 (0-1)',
    dropProb: '丢包概率 (MCAR)',
    noNumericParams: '无可用数值参数用于故障注入。',
    
    general: '常规',
    mqtt: 'MQTT',
    modbus: 'Modbus',
    
    mqttConfig: 'MQTT 配置',
    brokerHost: 'Broker 主机',
    brokerPort: 'Broker 端口',
    enableMqttPush: '启用 MQTT 推送',
    topicTemplate: 'Topic 模板',
    saveMqttSettings: '保存 MQTT 设置',
    
    modbusTcpServer: 'Modbus TCP 服务器',
    tcpPort: 'TCP 端口',
    enableModbusServer: '启用 Modbus 服务器',
    mappingInfo: '映射信息',
    saveModbusSettings: '保存 Modbus 设置',
    
    exportCsv: '导出 CSV',
    
    logicRules: '逻辑规则',
    addRule: '添加规则',
    condition: '条件',
    action: '动作',
    ruleHint: '例如: temp > 80',
    actionHint: '例如: status = "alarm"',
    createScenario: '创建 AI 场景',
    scenarioCreated: '场景创建成功',
    scenarioPrompt: "描述仿真场景（例如：“冷却液泄漏导致10秒后温度飙升”）。AI 将生成配置。",
    scenarioPlaceholder: '输入描述...',
    generate: '生成',
    aiPromptPlaceholder: "描述场景 (例如 '风扇故障导致过热')...",
    aiSuccess: "AI 场景生成成功",
    aiFailed: "AI 生成失败",
    
    // AI Batch Modal
    aiBatchGeneration: 'AI 批量生成',
    aiBatchDesc: '描述您想要生成的设备。请明确数量、类型和命名规则。',
    aiBatchPlaceholder: '例如：为 A 仓库创建 10 个温度传感器，按顺序编号。',
    aiBatchPoweredBy: '由当前活动的 LLM 提供支持 (Gemini/DeepSeek)',
    aiBatchButton: 'AI 批量生成',
  },
};
