import { Device } from './types';

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev_001',
    name: 'Industrial Diesel Generator',
    type: 'Generator',
    description: 'Main backup power unit for Sector 7.',
    status: 'stopped',
    currentScenario: 'Normal Operation',
    scenarios: ['Normal Operation', 'High Load', 'Fuel Line Blockage', 'Coolant Leak'],
    metrics: [
      { id: 'rpm', name: 'RPM', unit: 'rpm', min: 0, max: 3000 },
      { id: 'temp', name: 'Temperature', unit: '°C', min: 20, max: 120 },
      { id: 'voltage', name: 'Output Voltage', unit: 'V', min: 0, max: 480 },
      { id: 'vibration', name: 'Vibration', unit: 'mm/s', min: 0, max: 10 },
    ],
  },
  {
    id: 'dev_002',
    name: 'Plasma Cutter Arm',
    type: 'Cutter',
    description: 'Precision CNC plasma cutter.',
    status: 'stopped',
    currentScenario: 'Precision Cutting',
    scenarios: ['Precision Cutting', 'Rapid Traverse', 'Nozzle Clog', 'Arc Stability Loss'],
    metrics: [
      { id: 'current', name: 'Arc Current', unit: 'A', min: 0, max: 100 },
      { id: 'gasPressure', name: 'Gas Pressure', unit: 'psi', min: 0, max: 120 },
      { id: 'x_pos', name: 'X Position', unit: 'mm', min: 0, max: 1000 },
      { id: 'head_temp', name: 'Head Temp', unit: '°C', min: 20, max: 200 },
    ],
  },
];

export const DICTIONARY = {
  en: {
    title: 'DeviceSimulator',
    devices: 'Devices',
    addDevice: 'Add Device',
    running: 'Running',
    stopped: 'Stopped',
    simulationMode: 'Simulation Mode',
    modeAI: 'AI (Gemini)',
    modeLocal: 'Local (Physics)',
    scenario: 'Scenario',
    logs: 'System Logs',
    telemetry: 'Real-time Telemetry',
    start: 'Start',
    stop: 'Stop',
    create: 'Create',
    cancel: 'Cancel',
    name: 'Name',
    type: 'Type',
    scenarios: 'Scenarios (comma separated)',
    metrics: 'Metrics',
    dashboard: 'Dashboard',
    digitalTwin: '3D Digital Twin',
    systemSettingsGroup: 'System Settings',
    connectSettings: 'Connect Settings',
    deviceConfig: 'Device Config',
    categoryConfig: 'Category Config',
    modelConfig: 'Model Config',
    dashboardTitle: 'System Dashboard',
    noDescription: 'No description available.',
    realTimeMetrics: 'Real-time Metrics',
    switchGrid: 'Switch to Grid View',
    switchList: 'Switch to List View',
    waitingData: 'Waiting for data...',
    
    // Device Manager
    deviceManagement: 'Device Management',
    refresh: 'Refresh',
    newDevice: 'New Device',
    deleteDeviceConfirm: 'Are you sure you want to delete this device?',
    deleteFailed: 'Failed to delete device',
    saveFailed: 'Failed to save device',
    editDevice: 'Edit Device',
    createDevice: 'Create Device',
    basicInfo: 'Basic Info',
    parameters: 'Parameters',
    deviceName: 'Device Name',
    samplingRate: 'Sampling Rate (ms)',
    description: 'Description',
    defineMetrics: 'Define the metrics this device generates.',
    addParameter: 'Add Parameter',
    paramName: 'Name',
    paramType: 'Type',
    paramUnit: 'Unit',
    paramMin: 'Min',
    paramMax: 'Max',
    paramGenMode: 'Gen Mode',
    save: 'Save',
    loadParamsConfirm: 'Load parameters from this category template? This will replace current parameters.',
    noParams: 'No parameters defined. Add one to start generating data.',
    saveDevice: 'Save Device',
    
    // Category Manager
    categoryManagement: 'Category Management',
    syncSchema: 'Sync Schema',
    newCategory: 'New Category',
    syncConfirm: 'This will create Super Tables in TDengine for all categories. Continue?',
    deleteCategoryConfirm: 'Are you sure you want to delete this category? This may affect associated devices.',
    editCategory: 'Edit Category',
    createCategory: 'Create Category',
    categoryName: 'Category Name',
    categoryCode: 'Category Code (Unique)',
    paramJsonDef: 'Parameters (JSON Definition)',
    paramJsonHint: 'Define parameters as a JSON array. These will be used to create the TDengine Super Table schema.',
    synced: 'Synced',
    failed: 'Failed',
    checkConsole: 'Check console for details',
    saveCategory: 'Save Category',

    // System Manager
    systemStatusTitle: 'System Status & Configuration',
    dataGenService: 'Data Generation Service',
    dataGenDesc: 'Controls the global data generation engine. When running, all active devices will generate data according to their configuration.',
    startAllData: 'Start All Data Generation',
    stopAllData: 'Stop All Data Generation',
    tdengineIntegration: 'TDengine Integration',
    connected: 'Connected',
    disconnected: 'Disconnected',
    host: 'Host',
    port: 'Port',
    enableTdengine: 'Enable TDengine Storage',
    username: 'Username',
    password: 'Password',
    databaseName: 'Database Name',
    saveConfig: 'Save Configuration',
    testConnection: 'Test Connection',
    configSaved: 'Configuration saved successfully',
    connectionTestFailed: 'Connection test failed',
    
    // Simulation Model Manager
    modelManagement: 'Simulation Model Management',
    newModel: 'New Model',
    deleteModelConfirm: 'Are you sure you want to delete this simulation model?',
    editModel: 'Edit Simulation Model',
    createModel: 'Create Simulation Model',
    modelName: 'Model Name',
    configJson: 'Configuration (JSON)',
    saveModel: 'Save Model',

    // Log Viewer
    systemLogs: 'System Logs',
    noLogs: 'No logs generated yet.',

    // Add Device Modal
    addMetric: 'Add Metric',
    generic: 'Generic',
    generator: 'Generator',
    cutter: 'Cutter',
    customDeviceDesc: 'Custom user defined device',
    metricIdPlaceholder: 'ID (e.g. rpm)',
    metricNamePlaceholder: 'Name',
    metricUnitPlaceholder: 'Unit',
    twinSuffix: 'TWIN',
    syncPrefix: 'SYNC',
    
    // New Features
    advancedAndErrors: 'Advanced & Errors',
    globalPhysicsConfig: 'Global Physics Configuration',
    massKg: 'Mass (kg)',
    maxVelocity: 'Max Velocity (m/s)',
    paramErrorInjection: 'Parameter Error Injection',
    driftRate: 'Drift Rate (/sec)',
    anomalyProb: 'Anomaly Prob. (0-1)',
    dropProb: 'Drop Prob. (MCAR)',
    noNumericParams: 'No numeric parameters available for error injection.',
    
    general: 'General',
    mqtt: 'MQTT',
    modbus: 'Modbus',
    
    mqttConfig: 'MQTT Configuration',
    brokerHost: 'Broker Host',
    brokerPort: 'Broker Port',
    enableMqttPush: 'Enable MQTT Push',
    topicTemplate: 'Topic Template',
    saveMqttSettings: 'Save MQTT Settings',
    
    modbusTcpServer: 'Modbus TCP Server',
    tcpPort: 'TCP Port',
    enableModbusServer: 'Enable Modbus Server',
    mappingInfo: 'Mapping Info',
    saveModbusSettings: 'Save Modbus Settings',
    
    exportCsv: 'Export CSV',
    
    logicRules: 'Logic Rules',
    addRule: 'Add Rule',
    condition: 'Condition',
    action: 'Action',
    ruleHint: 'e.g. temp > 80',
    actionHint: 'e.g. status = "alarm"',
  },
  zh: {
    title: 'DeviceSimulator',
    devices: '设备列表',
    addDevice: '添加设备',
    running: '运行中',
    stopped: '已停止',
    simulationMode: '仿真模式',
    modeAI: 'AI 生成 (Gemini)',
    modeLocal: '本地引擎 (物理)',
    scenario: '运行场景',
    logs: '系统日志',
    telemetry: '实时遥测',
    start: '启动',
    stop: '停止',
    create: '创建',
    cancel: '取消',
    name: '设备名称',
    type: '类型',
    scenarios: '场景 (逗号分隔)',
    metrics: '指标',
    dashboard: '仪表盘',
    digitalTwin: '3D 数字孪生',
    systemSettingsGroup: '系统设置',
    connectSettings: '连接设置',
    deviceConfig: '设备配置',
    categoryConfig: '分类配置',
    modelConfig: '模型配置',
    dashboardTitle: '系统仪表盘',
    noDescription: '暂无描述',
    realTimeMetrics: '实时指标',
    switchGrid: '切换至网格视图',
    switchList: '切换至列表视图',
    waitingData: '等待数据...',

    // Device Manager
    deviceManagement: '设备管理',
    refresh: '刷新',
    newDevice: '新建设备',
    deleteDeviceConfirm: '确定要删除此设备吗？',
    deleteFailed: '删除设备失败',
    saveFailed: '保存设备失败',
    editDevice: '编辑设备',
    createDevice: '创建设备',
    basicInfo: '基本信息',
    parameters: '参数',
    deviceName: '设备名称',
    samplingRate: '采样率 (ms)',
    description: '描述',
    defineMetrics: '定义该设备生成的指标。',
    addParameter: '添加参数',
    paramName: '名称',
    paramType: '类型',
    paramUnit: '单位',
    paramMin: '最小值',
    paramMax: '最大值',
    paramGenMode: '生成模式',
    save: '保存',
    loadParamsConfirm: '从该分类模板加载参数？这将替换当前参数。',
    noParams: '未定义参数。添加一个以开始生成数据。',
    saveDevice: '保存设备',
    
    // Category Manager
    categoryManagement: '分类管理',
    syncSchema: '同步架构',
    newCategory: '新建分类',
    syncConfirm: '这将为所有分类在 TDengine 中创建超级表。继续？',
    deleteCategoryConfirm: '确定要删除此分类吗？这可能会影响关联设备。',
    editCategory: '编辑分类',
    createCategory: '创建分类',
    categoryName: '分类名称',
    categoryCode: '分类代码 (唯一)',
    paramJsonDef: '参数 (JSON 定义)',
    paramJsonHint: '将参数定义为 JSON 数组。这些将用于创建 TDengine 超级表架构。',
    synced: '已同步',
    failed: '失败',
    checkConsole: '查看控制台了解详情',
    saveCategory: '保存分类',

    // System Manager
    systemStatusTitle: '系统状态与配置',
    dataGenService: '数据生成服务',
    dataGenDesc: '控制全局数据生成引擎。运行时，所有活动设备将根据其配置生成数据。',
    startAllData: '启动所有数据生成',
    stopAllData: '停止所有数据生成',
    tdengineIntegration: 'TDengine 集成',
    connected: '已连接',
    disconnected: '未连接',
    host: '主机',
    port: '端口',
    enableTdengine: '启用 TDengine 存储',
    username: '用户名',
    password: '密码',
    databaseName: '数据库名称',
    saveConfig: '保存配置',
    testConnection: '测试连接',
    configSaved: '配置保存成功',
    connectionTestFailed: '连接测试失败',
    
    // Simulation Model Manager
    modelManagement: '仿真模型管理',
    newModel: '新建模型',
    deleteModelConfirm: '确定要删除此仿真模型吗？',
    editModel: '编辑仿真模型',
    createModel: '创建仿真模型',
    modelName: '模型名称',
    configJson: '配置 (JSON)',
    saveModel: '保存模型',

    // Log Viewer
    systemLogs: '系统日志',
    noLogs: '暂无日志。',

    // Add Device Modal
    addMetric: '添加指标',
    generic: '通用',
    generator: '发电机',
    cutter: '切割机',
    customDeviceDesc: '自定义设备',
    metricIdPlaceholder: 'ID (如 rpm)',
    metricNamePlaceholder: '名称',
    metricUnitPlaceholder: '单位',
    twinSuffix: '孪生',
    syncPrefix: '同步',
    
    // New Features
    advancedAndErrors: '高级与故障注入',
    globalPhysicsConfig: '全局物理配置',
    massKg: '质量 (kg)',
    maxVelocity: '最大速度 (m/s)',
    paramErrorInjection: '参数故障注入',
    driftRate: '漂移率 (/秒)',
    anomalyProb: '异常概率 (0-1)',
    dropProb: '丢包概率 (MCAR)',
    noNumericParams: '无可用数值参数用于故障注入。',
    
    general: '常规',
    mqtt: 'MQTT',
    modbus: 'Modbus',
    
    mqttConfig: 'MQTT 配置',
    brokerHost: 'Broker 主机',
    brokerPort: 'Broker 端口',
    enableMqttPush: '启用 MQTT 推送',
    topicTemplate: 'Topic 模板',
    saveMqttSettings: '保存 MQTT 设置',
    
    modbusTcpServer: 'Modbus TCP 服务器',
    tcpPort: 'TCP 端口',
    enableModbusServer: '启用 Modbus 服务器',
    mappingInfo: '映射信息',
    saveModbusSettings: '保存 Modbus 设置',
    
    exportCsv: '导出 CSV',
    
    logicRules: '逻辑规则',
    addRule: '添加规则',
    condition: '条件',
    action: '动作',
    ruleHint: '例如: temp > 80',
    actionHint: '例如: status = "alarm"',
  },
};
